// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: authentication/otp.proto

package otpGRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckEmailOTPInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CheckEmailOTPInput) Reset() {
	*x = CheckEmailOTPInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailOTPInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailOTPInput) ProtoMessage() {}

func (x *CheckEmailOTPInput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailOTPInput.ProtoReflect.Descriptor instead.
func (*CheckEmailOTPInput) Descriptor() ([]byte, []int) {
	return file_authentication_otp_proto_rawDescGZIP(), []int{0}
}

func (x *CheckEmailOTPInput) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CheckEmailOTPInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckEmailOTPResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CheckEmailOTPResult) Reset() {
	*x = CheckEmailOTPResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_otp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailOTPResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailOTPResult) ProtoMessage() {}

func (x *CheckEmailOTPResult) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_otp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailOTPResult.ProtoReflect.Descriptor instead.
func (*CheckEmailOTPResult) Descriptor() ([]byte, []int) {
	return file_authentication_otp_proto_rawDescGZIP(), []int{1}
}

func (x *CheckEmailOTPResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SendEmailOTPInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendEmailOTPInput) Reset() {
	*x = SendEmailOTPInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_otp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailOTPInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailOTPInput) ProtoMessage() {}

func (x *SendEmailOTPInput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_otp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailOTPInput.ProtoReflect.Descriptor instead.
func (*SendEmailOTPInput) Descriptor() ([]byte, []int) {
	return file_authentication_otp_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailOTPInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendEmailOTPResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SendEmailOTPResult) Reset() {
	*x = SendEmailOTPResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_otp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailOTPResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailOTPResult) ProtoMessage() {}

func (x *SendEmailOTPResult) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_otp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailOTPResult.ProtoReflect.Descriptor instead.
func (*SendEmailOTPResult) Descriptor() ([]byte, []int) {
	return file_authentication_otp_proto_rawDescGZIP(), []int{3}
}

func (x *SendEmailOTPResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_authentication_otp_proto protoreflect.FileDescriptor

var file_authentication_otp_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x74, 0x70, 0x47,
	0x52, 0x50, 0x43, 0x22, 0x3e, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x4f, 0x54, 0x50, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x65,
	0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0xa5, 0x01, 0x0a, 0x0a,
	0x4f, 0x54, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50, 0x12, 0x1b, 0x2e, 0x6f, 0x74,
	0x70, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x4f, 0x54, 0x50, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x74, 0x70, 0x47, 0x52,
	0x50, 0x43, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50, 0x12, 0x1a, 0x2e, 0x6f, 0x74, 0x70, 0x47, 0x52,
	0x50, 0x43, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1b, 0x2e, 0x6f, 0x74, 0x70, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x67, 0x74, 0x72, 0x61, 0x6e, 0x38, 0x38, 0x2f, 0x61, 0x6e,
	0x69, 0x66, 0x6e, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x74, 0x70, 0x47, 0x52, 0x50,
	0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authentication_otp_proto_rawDescOnce sync.Once
	file_authentication_otp_proto_rawDescData = file_authentication_otp_proto_rawDesc
)

func file_authentication_otp_proto_rawDescGZIP() []byte {
	file_authentication_otp_proto_rawDescOnce.Do(func() {
		file_authentication_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_authentication_otp_proto_rawDescData)
	})
	return file_authentication_otp_proto_rawDescData
}

var file_authentication_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authentication_otp_proto_goTypes = []interface{}{
	(*CheckEmailOTPInput)(nil),  // 0: otpGRPC.CheckEmailOTPInput
	(*CheckEmailOTPResult)(nil), // 1: otpGRPC.CheckEmailOTPResult
	(*SendEmailOTPInput)(nil),   // 2: otpGRPC.SendEmailOTPInput
	(*SendEmailOTPResult)(nil),  // 3: otpGRPC.SendEmailOTPResult
}
var file_authentication_otp_proto_depIdxs = []int32{
	0, // 0: otpGRPC.OTPService.CheckEmailOTP:input_type -> otpGRPC.CheckEmailOTPInput
	2, // 1: otpGRPC.OTPService.SendEmailOTP:input_type -> otpGRPC.SendEmailOTPInput
	1, // 2: otpGRPC.OTPService.CheckEmailOTP:output_type -> otpGRPC.CheckEmailOTPResult
	3, // 3: otpGRPC.OTPService.SendEmailOTP:output_type -> otpGRPC.SendEmailOTPResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_otp_proto_init() }
func file_authentication_otp_proto_init() {
	if File_authentication_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authentication_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailOTPInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_otp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailOTPResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_otp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailOTPInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_otp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailOTPResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authentication_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_otp_proto_goTypes,
		DependencyIndexes: file_authentication_otp_proto_depIdxs,
		MessageInfos:      file_authentication_otp_proto_msgTypes,
	}.Build()
	File_authentication_otp_proto = out.File
	file_authentication_otp_proto_rawDesc = nil
	file_authentication_otp_proto_goTypes = nil
	file_authentication_otp_proto_depIdxs = nil
}
